### ISSUE TITLE
Can't figure out how to create a user

### ISSUE THREAD

**Issue by schtinkafinga** [qdm12/meemo#6]
I've installed the Meemo, It seems to be up and running. But i can't figure out how to add a user.

`./commands.sh add username password` doesn't seem to do anything, considering the fact that after adding a user i get error at the meemo page saying about invalid credintials

running `./commands.sh ls` prints out information about users not existing, even though i created one not too long ago.

```
root@Theo:~/meemo# ./commands.sh ls
./commands.sh: 3: [: !=: unexpected operator
====== List of users ======
Using local auth file:  /users.json
No users. Use `admin user-add` to add some.
```

**Comment by qdm12** [comment]
Maybe your shell doesn't understand the script (for example `./commands.sh: 3: [: !=: unexpected operator` seems odd)

> considering the fact that after adding a user i get error at the meemo page saying about invalid credintials

Can you comment with the error you get?

If you have a look at the [script](https://github.com/qdm12/meemo/blob/master/commands.sh), you can try adding a user directly using the docker command:

```sh
USER=youruser
PASSWORD=yourpassword
docker-compose exec meemo ./meemo/admin user-add -u $USER -p $PASSWORD --display-name $USER;;
```

Let me know the outcome, thanks for taking the time to create the issue.

**Comment by espressoelf** [comment]
Had the same error: `./commands.sh: 3: [: !=: unexpected operator`

Doing some quick searching, this seems to be because different distros link `sh` to different shells. On Alpine, it links to `ash`, `dash` on my Debian (producing above error) and on OpenSUSE via `/etc/alternatives/sh` ultimatively to `bash`. 

Simple fix: Edit the first line of `commands.sh` to `#!/bin/bash` :)

About the credentials: This repo's readme states to `chmod 400 users.json` which makes the file read-only. Permissions need to be 600 so the owner (1000, i.e. not root) can write to it.

~Still can't login, though. Trying do get more info.~ Had a typo in the .env.

**Comment by qdm12** [comment]
@espressoelf Thanks! I've updated the script to use `/bin/bash` and the readme to `chmod 600 users.json`.
