### ISSUE TITLE
Can't add users at all

### ISSUE THREAD

**Issue by nickm324** [qdm12/meemo#9]
When I try to add a user it always returns an error saying missing display name when it is clearly provided.
![image](https://user-images.githubusercontent.com/6774571/158075246-b44c1a82-3e7f-4021-8ac5-257be3edd406.png)

**Comment by nickm324** [comment]
Figured out the issue, you cannot use a $ in your password. Once I removed it from $Pudsmckenzie and replaced the $ with a capital S it worked.

**Comment by mmk01569** [comment]
@nickm324 , I'm having the same problem, but no special characters in my password. Can I ask what directory you created your users.json file in? And did you need to update docker-compose.yml to match the location of the users.json?

**Comment by qdm12** [comment]
The admin scripts are from https://github.com/cloudron-io/meemo directly, so you might want to ask on this repo instead of here. I merely just setup a Docker image and CI around their program.

@mmk01569 I think the instructions in the readme of this repo should be clear on what to do, but feel free to suggest improvements if you think anything is confusing.
